# Generated by Django 4.2.8 on 2023-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlstockdata',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
